modLoader = "javafml"
loaderVersion = "[28,)"
license="MIT"
[[mods]]
modId = "info_is_power"
version = "${file.jarVersion}"
displayName = "Info Is Power!"
displayURL="https://github.com/ChAoSUnItY/InfoIsPower"
logoFile="logo.png"
authors="ChAoS_UnItY"
description = '''
A simple HUD mod with several useful details.
'''